server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://nagendram:admin123@fitnessdb.2ykb3kn.mongodb.net/?retryWrites=true&w=majority&appName=FitnessDB
      database: fitnessdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking