server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb+srv://nagendram:admin123@fitnessdb.2ykb3kn.mongodb.net/?retryWrites=true&w=majority&appName=FitnessDB
      database: fitnessrecommendation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: true
rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
